version: "3.8"

services:
  web:
    build: .
    command: bash -c "alembic -c app/alembic.ini upgrade head && uvicorn app.main:app --reload --host 0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app/
    environment:
      - SQL_USER=postgres
      - SQL_PASSWORD=password
      - SQL_DATABASE=postgres
      - SQL_HOST=pgdb
    depends_on:
      - pgdb
    restart: on-failure
  pgdb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
